/**:
  ros__parameters:
    moveit_simple_controller_manager:
      controller_names:
        - joint_trajectory_controller

      joint_trajectory_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - arm_joint_1
          - arm_joint_2
          - arm_joint_3
          - arm_joint_4
          - arm_joint_5
          - arm_joint_6
