/**:
  ros__parameters:
    ar_manipulator:
      kinematics_solver: bio_ik/BioIKKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.05
      kinematics_solver_attempts: 1
      minimal_displacement_weight: 5.0
      center_joints_weight: 2.0
      avoid_joint_limits_weight: 1.0
      rotation_scale: 0.5
