/**:
  ros__parameters:
    ar_manipulator:
      kinematics_solver: bio_ik/BioIKKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      mode: gd_c
      minimal_displacement_weight: 10.0
      center_joints_weight: 0.1
      avoid_joint_limits_weight: 1.0
      rotation_scale: 0.5
